--- a/.github/workflows/analyze.yaml
+++ b/.github/workflows/analyze.yaml
@@ -22,4 +22,4 @@
       with:
         languages: go
     - uses: github/codeql-action/autobuild@a589d4087ea22a0a48fc153d1b461886e262e0f2 # v2.2.7
-    - uses: github/codeql-action/analyze@a589d4087ea22a0a48fc153d1b461886e262e0f2 # v2.2.7
+    - uses: github/codeql-action/analyze@a589d4087ea22a0a48fc153d1b461886e262e0f2 # v2.2.7